spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

auth:
  access-cookie-secure: false
  csrf-cookie-secure: false
  refresh-cookie-secure: false

file:
  public-base-url: http://localhost:8080/files
  storage:
    type: local
    bucket: onfilm-media
    root: /Users/whheo/Desktop/onfilm/local-storage
    presign-expiration-minutes: 10

app:
  kafka:
    topic:
      media-encode-requested: media.encode.requested
