spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  storage:
    type: s3
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
  public-base-url: ${S3_PUBLIC_BASE_URL:}

auth:
  access-cookie-secure: true
  csrf-cookie-secure: true
  refresh-cookie-secure: true
